/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author hamza
 */
@Entity
public class Creneau {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idCreneau;

    @Basic
    private String debut;

    @Basic
    private String fin;

    @ManyToMany(targetEntity = Jour.class, mappedBy = "creneaus")
    private List<Jour> jours;

    @ManyToMany(targetEntity = Professeur.class, mappedBy = "creneaux")
    private List<Professeur> professeurs;

    public Long getIdCreneau() {
        return this.idCreneau;
    }

    public void setIdCreneau(Long idCreneau) {
        this.idCreneau = idCreneau;
    }

    public String getDebut() {
        return this.debut;
    }

    public void setDebut(String debut) {
        this.debut = debut;
    }

    public String getFin() {
        return this.fin;
    }

    public void setFin(String fin) {
        this.fin = fin;
    }

    public List<Jour> getJours() {
        return this.jours;
    }

    public void setJours(List<Jour> jours) {
        this.jours = jours;
    }

    public List<Professeur> getProfesseurs() {
        return this.professeurs;
    }

    public void setProfesseurs(List<Professeur> professeurs) {
        this.professeurs = professeurs;
    }

}
