/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author hamza
 */
@Entity
public class Niveau_Etude {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idNiveauEtude;

    @Basic
    private String nomNiveauEtude;

    @OneToMany(targetEntity = Annee_Etude.class)
    private List<Annee_Etude> annee_Etudes;

    @OneToMany(targetEntity = Type_Etude.class)
    private List<Type_Etude> type_Etudes;

    public Long getIdNiveauEtude() {
        return this.idNiveauEtude;
    }

    public void setIdNiveauEtude(Long idNiveauEtude) {
        this.idNiveauEtude = idNiveauEtude;
    }

    public String getNomNiveauEtude() {
        return this.nomNiveauEtude;
    }

    public void setNomNiveauEtude(String nomNiveauEtude) {
        this.nomNiveauEtude = nomNiveauEtude;
    }

    public List<Annee_Etude> getAnnee_Etudes() {
        return this.annee_Etudes;
    }

    public void setAnnee_Etudes(List<Annee_Etude> annee_Etudes) {
        this.annee_Etudes = annee_Etudes;
    }

    public List<Type_Etude> getType_Etudes() {
        return this.type_Etudes;
    }

    public void setType_Etudes(List<Type_Etude> type_Etudes) {
        this.type_Etudes = type_Etudes;
    }

}
