/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author hamza
 */
@Entity
public class Type_Etude {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idTypeEtude;

    @Basic
    private String nomTypeEtude;

    @ManyToMany(targetEntity = Annee_Etude.class, mappedBy = "type_Etudes")
    private List<Annee_Etude> annee_Etudes;

    public Long getIdTypeEtude() {
        return this.idTypeEtude;
    }

    public void setIdTypeEtude(Long idTypeEtude) {
        this.idTypeEtude = idTypeEtude;
    }

    public String getNomTypeEtude() {
        return this.nomTypeEtude;
    }

    public void setNomTypeEtude(String nomTypeEtude) {
        this.nomTypeEtude = nomTypeEtude;
    }

    public List<Annee_Etude> getAnnee_Etudes() {
        return this.annee_Etudes;
    }

    public void setAnnee_Etudes(List<Annee_Etude> annee_Etudes) {
        this.annee_Etudes = annee_Etudes;
    }

}
