/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author hamza
 */
@Entity
public class Annee_Etude {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idAnneeEtude;

    @Basic
    private String nomAnneeEtude;

    @ManyToMany(targetEntity = Type_Etude.class)
    private List<Type_Etude> type_Etudes;

    public Long getIdAnneeEtude() {
        return this.idAnneeEtude;
    }

    public void setIdAnneeEtude(Long idAnneeEtude) {
        this.idAnneeEtude = idAnneeEtude;
    }

    public String getNomAnneeEtude() {
        return this.nomAnneeEtude;
    }

    public void setNomAnneeEtude(String nomAnneeEtude) {
        this.nomAnneeEtude = nomAnneeEtude;
    }

    public List<Type_Etude> getType_Etudes() {
        return this.type_Etudes;
    }

    public void setType_Etudes(List<Type_Etude> type_Etudes) {
        this.type_Etudes = type_Etudes;
    }

}
