/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 * @author hamza
 */
@Entity
public class Client extends User {

    @Basic
    private String ecole;

    @OneToMany(targetEntity = Type_Etude.class)
    private List<Type_Etude> type_Etudes;

    @OneToMany(targetEntity = Annee_Etude.class)
    private List<Annee_Etude> annee_Etudes;

    @ManyToMany(targetEntity = Pack.class, mappedBy = "clients")
    private List<Pack> packs;

    @ManyToMany(targetEntity = Reservation.class)
    private List<Reservation> reservations;

    public String getEcole() {
        return this.ecole;
    }

    public void setEcole(String ecole) {
        this.ecole = ecole;
    }

    public List<Type_Etude> getType_Etudes() {
        return this.type_Etudes;
    }

    public void setType_Etudes(List<Type_Etude> type_Etudes) {
        this.type_Etudes = type_Etudes;
    }

    public List<Annee_Etude> getAnnee_Etudes() {
        return this.annee_Etudes;
    }

    public void setAnnee_Etudes(List<Annee_Etude> annee_Etudes) {
        this.annee_Etudes = annee_Etudes;
    }

    public List<Pack> getPacks() {
        return this.packs;
    }

    public void setPacks(List<Pack> packs) {
        this.packs = packs;
    }

    public List<Reservation> getReservations() {
        return this.reservations;
    }

    public void setReservations(List<Reservation> reservations) {
        this.reservations = reservations;
    }

}
