/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author hamza
 */
@Entity
public class Matiere {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idMatiere;

    @Basic
    private String nomMatiere;

    @OneToMany(targetEntity = Seance.class)
    private List<Seance> seances;

    public Long getIdMatiere() {
        return this.idMatiere;
    }

    public void setIdMatiere(Long idMatiere) {
        this.idMatiere = idMatiere;
    }

    public String getNomMatiere() {
        return this.nomMatiere;
    }

    public void setNomMatiere(String nomMatiere) {
        this.nomMatiere = nomMatiere;
    }

    public List<Seance> getSeances() {
        return this.seances;
    }

    public void setSeances(List<Seance> seances) {
        this.seances = seances;
    }

}
