/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 * @author hamza
 */
@Entity
public class Pack {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idPack;

    @Basic
    private String localisation;

    @Basic
    private String nomPack;

    @Basic
    private String description;

    @Basic
    private String nbrTickets;

    @OneToMany(targetEntity = Type_Etude.class)
    private List<Type_Etude> type_Etudes;

    @OneToMany(targetEntity = Matiere.class)
    private List<Matiere> matieres;

    @OneToMany(targetEntity = Reservation.class)
    private List<Reservation> reservations;

    @ManyToMany(targetEntity = Client.class)
    private List<Client> clients;

    public Long getIdPack() {
        return this.idPack;
    }

    public void setIdPack(Long idPack) {
        this.idPack = idPack;
    }

    public String getLocalisation() {
        return this.localisation;
    }

    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }

    public String getNomPack() {
        return this.nomPack;
    }

    public void setNomPack(String nomPack) {
        this.nomPack = nomPack;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getNbrTickets() {
        return this.nbrTickets;
    }

    public void setNbrTickets(String nbrTickets) {
        this.nbrTickets = nbrTickets;
    }

    public List<Type_Etude> getType_Etudes() {
        return this.type_Etudes;
    }

    public void setType_Etudes(List<Type_Etude> type_Etudes) {
        this.type_Etudes = type_Etudes;
    }

    public List<Matiere> getMatieres() {
        return this.matieres;
    }

    public void setMatieres(List<Matiere> matieres) {
        this.matieres = matieres;
    }

    public List<Reservation> getReservations() {
        return this.reservations;
    }

    public void setReservations(List<Reservation> reservations) {
        this.reservations = reservations;
    }

    public List<Client> getClients() {
        return this.clients;
    }

    public void setClients(List<Client> clients) {
        this.clients = clients;
    }

}
