/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;

/**
 * @author hamza
 */
@Entity
public class Professeur extends User {

    @Basic
    private String experience;

    @OneToMany(targetEntity = Matiere.class)
    private List<Matiere> matieres;

    @ManyToMany(targetEntity = Annee_Etude.class)
    private List<Annee_Etude> annee_Etudes;

    @ManyToMany(targetEntity = Jour.class)
    private List<Jour> jours;

    @ManyToMany(targetEntity = Creneau.class)
    private List<Creneau> creneaux;

    public String getExperience() {
        return this.experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    public List<Matiere> getMatieres() {
        return this.matieres;
    }

    public void setMatieres(List<Matiere> matieres) {
        this.matieres = matieres;
    }

    public List<Annee_Etude> getAnnee_Etudes() {
        return this.annee_Etudes;
    }

    public void setAnnee_Etudes(List<Annee_Etude> annee_Etudes) {
        this.annee_Etudes = annee_Etudes;
    }

    public List<Jour> getJours() {
        return this.jours;
    }

    public void setJours(List<Jour> jours) {
        this.jours = jours;
    }

    public List<Creneau> getCreneaux() {
        return this.creneaux;
    }

    public void setCreneaux(List<Creneau> creneaux) {
        this.creneaux = creneaux;
    }

}
