/**
 * This file was generated by the Jeddict
 */
package com.eurekour.entities;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author hamza
 */
@Entity
public class Seance {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idSeance;

    @Basic
    private String heureSeance;

    @Basic
    private String dateSeance;

    @Basic
    private String statut;

    @Basic
    private String idProfesseur;

    public Long getIdSeance() {
        return this.idSeance;
    }

    public void setIdSeance(Long idSeance) {
        this.idSeance = idSeance;
    }

    public String getHeureSeance() {
        return this.heureSeance;
    }

    public void setHeureSeance(String heureSeance) {
        this.heureSeance = heureSeance;
    }

    public String getDateSeance() {
        return this.dateSeance;
    }

    public void setDateSeance(String dateSeance) {
        this.dateSeance = dateSeance;
    }

    public String getStatut() {
        return this.statut;
    }

    public void setStatut(String statut) {
        this.statut = statut;
    }

    public String getIdProfesseur() {
        return this.idProfesseur;
    }

    public void setIdProfesseur(String idProfesseur) {
        this.idProfesseur = idProfesseur;
    }

}
